### ISSUE TITLE
Reproducing the evaluation results in the paper

### ISSUE THREAD

**Issue by yuchenlin** [iesl/protoqa-evaluator#1]
Hi,

Thanks for the great dataset and evaluation scripts.

I was wondering if there is a toy example for the `targets.jsonl`.

I saw this line ```The targets.jsonl file should be in the evaluation format from https://github.com/iesl/protoqa-data.```, but I'm not sure which file is the so-called `evaluation format` . 

For example, if I want to evaluate `data/dev/dev.predictions.gpt2finetuned.json` over the `data/dev/dev.crowdsourced.jsonl`, what should be the command lines, such that I can reproduce the experimental results table in the paper? 

Thanks very much in advance.  @mboratko

**Comment by mboratko** [comment]
The command to use is `protoqa_evaluator evaluate`, which has help information available for the options / arguments.

For example, to use the exact_match similarity metric you can run

```
protoqa_evaluator evaluate --similarity_function exact_match data/dev/dev.crowdsourced.jsonl data/dev/dev.predictions.gpt2finetuned.json
```

For WordNet, you can run
```
protoqa_evaluator evaluate --similarity_function wordnet data/dev/dev.crowdsourced.jsonl data/dev/dev.predictions.gpt2finetuned.json
```

I will leave this open until we can add these examples to the README to make this clearer.

**Comment by mboratko** [comment]
Upon reinspection I noticed this already was in the README, so I am closing this issue. Please let me know if you have further questions.
