### ISSUE TITLE
no maxinc3 in protoqa_evaluator.evaluation

### ISSUE THREAD

**Issue by yuchenlin** [iesl/protoqa-evaluator#2]
Hi,

I am trying to follow the instruction in the readme 

```
from protoqa_evaluator.data_processing import load_question_answer_clusters_from_jsonl
from protoqa_evaluator.evaluation import evaluate, maxinc3
```
However, it reports
ImportError: cannot import name '**maxinc3**' from 'protoqa_evaluator.evaluation' (/path/to/protoqa-evaluator/src/protoqa_evaluator/evaluation.py)

**Comment by yuchenlin** [comment]
It seems that the whole codebase does not have a definition of this `maxinc3` function.

**Comment by mboratko** [comment]
The README file was a bit outdated compared to the current code repo. In 1f8cfeac I have refactored this to put all the evaluations you might need in the `common_evaluations.py` file, and also updated the README to reflect these changes.

**Comment by yuchenlin** [comment]
Thanks!
